INSERT INTO public.assets (symbol, name, sector, market) VALUES
-- IBEX 35
('ITX.MC', 'Inditex', 'Consumo Cíclico', 'IBEX 35'),
('SAN.MC', 'Banco Santander', 'Finanzas', 'IBEX 35'),
('IBE.MC', 'Iberdrola', 'Servicios Públicos', 'IBEX 35'),
('BBVA.MC', 'BBVA', 'Finanzas', 'IBEX 35'),
('TEF.MC', 'Telefónica', 'Comunicaciones', 'IBEX 35'),
('CABK.MC', 'CaixaBank', 'Finanzas', 'IBEX 35'),
('AMS.MC', 'Amadeus IT Group', 'Tecnología', 'IBEX 35'),
('REP.MC', 'Repsol', 'Energía', 'IBEX 35'),
('FER.MC', 'Ferrovial', 'Industria', 'IBEX 35'),
('AENA.MC', 'Aena', 'Industria', 'IBEX 35'),
('CLNX.MC', 'Cellnex Telecom', 'Comunicaciones', 'IBEX 35'),
('NTGY.MC', 'Naturgy Energy Group', 'Servicios Públicos', 'IBEX 35'),
('ELE.MC', 'Endesa', 'Servicios Públicos', 'IBEX 35'),
('GRF.MC', 'Grifols', 'Salud', 'IBEX 35'),
('IAG.MC', 'International Consolidated Airlines', 'Industria', 'IBEX 35'),
('ACS.MC', 'ACS', 'Industria', 'IBEX 35'),
('RED.MC', 'Redeia', 'Servicios Públicos', 'IBEX 35'),
('MAP.MC', 'Mapfre', 'Finanzas', 'IBEX 35'),
('BKT.MC', 'Bankinter', 'Finanzas', 'IBEX 35'),
('ENG.MC', 'Enagás', 'Servicios Públicos', 'IBEX 35'),
('SAB.MC', 'Banco Sabadell', 'Finanzas', 'IBEX 35'),
('LOG.MC', 'Logista', 'Industria', 'IBEX 35'),
('MRL.MC', 'Merlin Properties', 'Inmobiliario', 'IBEX 35'),
('COL.MC', 'Inmobiliaria Colonial', 'Inmobiliario', 'IBEX 35'),
('SCYR.MC', 'Sacyr', 'Industria', 'IBEX 35'),
('ANA.MC', 'Acciona', 'Industria', 'IBEX 35'),
('ANE.MC', 'Acciona Energía', 'Servicios Públicos', 'IBEX 35'),
('UNI.MC', 'Unicaja Banco', 'Finanzas', 'IBEX 35'),
('ROVI.MC', 'Laboratorios Rovi', 'Salud', 'IBEX 35'),
('FDR.MC', 'Fluidra', 'Industria', 'IBEX 35'),
('IDR.MC', 'Indra Sistemas', 'Tecnología', 'IBEX 35'),
('SLR.MC', 'Solaria Energía y Medio Ambiente', 'Servicios Públicos', 'IBEX 35'),
('MTS.MC', 'ArcelorMittal', 'Materiales Básicos', 'IBEX 35'),
('ACX.MC', 'Acerinox', 'Materiales Básicos', 'IBEX 35'),
('MEL.MC', 'Meliá Hotels International', 'Consumo Cíclico', 'IBEX 35'),

-- Mercado Continuo
('VID.MC', 'Vidrala', 'Industria', 'Continuo'),
('VIS.MC', 'Viscofan', 'Consumo Defensivo', 'Continuo'),
('EBRO.MC', 'Ebro Foods', 'Consumo Defensivo', 'Continuo'),
('CAF.MC', 'Construcciones y Auxiliar de Ferrocarriles', 'Industria', 'Continuo'),
('GEST.MC', 'Gestamp Automoción', 'Consumo Cíclico', 'Continuo'),
('TLGO.MC', 'Talgo', 'Industria', 'Continuo'),
('PHM.MC', 'PharmaMar', 'Salud', 'Continuo'),
('ALM.MC', 'Almirall', 'Salud', 'Continuo'),
('FCC.MC', 'Fomento de Construcciones y Contratas', 'Industria', 'Continuo'),
('CIE.MC', 'CIE Automotive', 'Consumo Cíclico', 'Continuo'),
('EDR.MC', 'eDreams ODIGEO', 'Consumo Cíclico', 'Continuo'),
('DIA.MC', 'Distribuidora Internacional de Alimentación', 'Consumo Defensivo', 'Continuo'),
('OHLA.MC', 'OHLA', 'Industria', 'Continuo'),
('TUB.MC', 'Tubacex', 'Materiales Básicos', 'Continuo'),
('TRE.MC', 'Técnicas Reunidas', 'Industria', 'Continuo'),

-- BME Growth
('LLE.MC', 'Lleida.net', 'Tecnología', 'BME Growth'),
('HLZ.MC', 'Holaluz', 'Servicios Públicos', 'BME Growth'),
('GIG.MC', 'Gigas Hosting', 'Tecnología', 'BME Growth'),
('TR1.MC', 'Tier1 Technology', 'Tecnología', 'BME Growth'),
('IZER.MC', 'Izertis', 'Tecnología', 'BME Growth'),
('EIDF.MC', 'EiDF Solar', 'Servicios Públicos', 'BME Growth'),
('ADL.MC', 'ADL Bionatur Solutions', 'Salud', 'BME Growth'),
('AGIL.MC', 'Agile Content', 'Tecnología', 'BME Growth'),
('CCOM.MC', 'Cuatroochenta', 'Tecnología', 'BME Growth')

ON CONFLICT (symbol) DO UPDATE
SET
  name = EXCLUDED.name,
  sector = EXCLUDED.sector,
  market = EXCLUDED.market;
