-- Seed data for assets table (IBEX 35, Mercado Continuo, BME Growth)
-- Idempotent inserts using ON CONFLICT (symbol) DO UPDATE

INSERT INTO public.assets (symbol, name, sector, market)
VALUES
  ('ITX.MC', 'Inditex', 'Consumer Cyclical', 'IBEX 35'),
  ('SAN.MC', 'Banco Santander', 'Financials', 'IBEX 35'),
  ('BBVA.MC', 'Banco Bilbao Vizcaya Argentaria', 'Financials', 'IBEX 35'),
  ('IBE.MC', 'Iberdrola', 'Utilities', 'IBEX 35'),
  ('TEF.MC', 'Telefónica', 'Communication Services', 'IBEX 35'),
  ('CABK.MC', 'CaixaBank', 'Financials', 'IBEX 35'),
  ('REP.MC', 'Repsol', 'Energy', 'IBEX 35'),
  ('AMS.MC', 'Amadeus IT Group', 'Technology', 'IBEX 35'),
  ('AENA.MC', 'Aena', 'Industrials', 'IBEX 35'),
  ('FER.MC', 'Ferrovial', 'Industrials', 'IBEX 35'),
  ('ENG.MC', 'Enagás', 'Utilities', 'IBEX 35'),
  ('ELE.MC', 'Endesa', 'Utilities', 'IBEX 35'),
  ('NTGY.MC', 'Naturgy Energy Group', 'Utilities', 'IBEX 35'),
  ('RED.MC', 'Redeia', 'Utilities', 'IBEX 35'),
  ('ACS.MC', 'ACS', 'Industrials', 'IBEX 35'),
  ('ANA.MC', 'Acciona', 'Industrials', 'IBEX 35'),
  ('BKT.MC', 'Bankinter', 'Financials', 'IBEX 35'),
  ('SAB.MC', 'Banco Sabadell', 'Financials', 'IBEX 35'),
  ('IAG.MC', 'International Consolidated Airlines Group', 'Industrials', 'IBEX 35'),
  ('GRF.MC', 'Grifols', 'Healthcare', 'IBEX 35'),
  ('MTS.MC', 'ArcelorMittal', 'Basic Materials', 'IBEX 35'),
  ('ACX.MC', 'Acerinox', 'Basic Materials', 'IBEX 35'),
  ('MAP.MC', 'Mapfre', 'Financials', 'IBEX 35'),
  ('COL.MC', 'Colonial', 'Real Estate', 'IBEX 35'),
  ('MRL.MC', 'Merlin Properties', 'Real Estate', 'IBEX 35'),
  ('CLNX.MC', 'Cellnex Telecom', 'Communication Services', 'IBEX 35'),
  ('FLUI.MC', 'Fluidra', 'Industrials', 'IBEX 35'),
  ('ROVI.MC', 'Laboratorios Farmacéuticos Rovi', 'Healthcare', 'IBEX 35'),
  ('LOG.MC', 'Logista', 'Industrials', 'IBEX 35'),
  ('UNI.MC', 'Unicaja Banco', 'Financials', 'IBEX 35'),
  ('SACYR.MC', 'Sacyr', 'Industrials', 'IBEX 35'),
  ('MEL.MC', 'Meliá Hotels International', 'Consumer Cyclical', 'IBEX 35'),
  ('EBRO.MC', 'Ebro Foods', 'Consumer Defensive', 'Continuo'),
  ('ALM.MC', 'Almirall', 'Healthcare', 'Continuo'),
  ('CAF.MC', 'CAF', 'Industrials', 'Continuo'),
  ('VIS.MC', 'Viscofan', 'Consumer Defensive', 'Continuo'),
  ('GCO.MC', 'Grupo Catalana Occidente', 'Financials', 'Continuo'),
  ('CIE.MC', 'CIE Automotive', 'Consumer Cyclical', 'Continuo'),
  ('VID.MC', 'Vidrala', 'Consumer Cyclical', 'Continuo'),
  ('PHM.MC', 'PharmaMar', 'Healthcare', 'Continuo'),
  ('TRE.MC', 'Técnicas Reunidas', 'Energy', 'Continuo'),
  ('TLGO.MC', 'Talgo', 'Industrials', 'Continuo'),
  ('TUB.MC', 'Tubacex', 'Basic Materials', 'Continuo'),
  ('TRG.MC', 'Tubos Reunidos', 'Basic Materials', 'Continuo'),
  ('DIA.MC', 'DIA', 'Consumer Defensive', 'Continuo'),
  ('ENC.MC', 'Ence', 'Basic Materials', 'Continuo'),
  ('FCC.MC', 'FCC', 'Industrials', 'Continuo'),
  ('LLE.MC', 'Lleida.net', 'Technology', 'BME Growth'),
  ('GIG.MC', 'Gigas Hosting', 'Technology', 'BME Growth'),
  ('ICOM.MC', 'Izertis', 'Technology', 'BME Growth'),
  ('ARTE.MC', 'Arteche', 'Industrials', 'BME Growth'),
  ('END.MC', 'Endurance Motive', 'Industrials', 'BME Growth'),
  ('HLZ.MC', 'Holaluz', 'Utilities', 'BME Growth'),
  ('EAS.MC', 'Enerside Energy', 'Utilities', 'BME Growth'),
  ('AGIL.MC', 'Agile Content', 'Technology', 'BME Growth'),
  ('CCOM.MC', 'Catenon', 'Industrials', 'BME Growth'),
  ('TR1.MC', 'Tier1 Technology', 'Technology', 'BME Growth'),
  ('SNG.MC', 'SNGULAR', 'Technology', 'BME Growth'),
  ('MIO.MC', 'MioGroup', 'Communication Services', 'BME Growth')
ON CONFLICT (symbol) DO UPDATE SET
  name = EXCLUDED.name,
  sector = EXCLUDED.sector,
  market = EXCLUDED.market,
  updated_at = NOW();
