-- Script para poblar la tabla assets con activos españoles
INSERT INTO public.assets (symbol, name, sector, market)
VALUES
  ('ITX.MC', 'Inditex', 'Consumo Cíclico', 'IBEX 35'),
  ('SAN.MC', 'Banco Santander', 'Finanzas', 'IBEX 35'),
  ('IBE.MC', 'Iberdrola', 'Energía', 'IBEX 35'),
  ('BBVA.MC', 'BBVA', 'Finanzas', 'IBEX 35'),
  ('AMS.MC', 'Amadeus IT Group', 'Tecnología', 'IBEX 35'),
  ('CLNX.MC', 'Cellnex Telecom', 'Telecomunicaciones', 'IBEX 35'),
  ('TEF.MC', 'Telefónica', 'Telecomunicaciones', 'IBEX 35'),
  ('FER.MC', 'Ferrovial', 'Industria', 'IBEX 35'),
  ('AENA.MC', 'Aena', 'Industria', 'IBEX 35'),
  ('REP.MC', 'Repsol', 'Energía', 'IBEX 35'),
  ('CABK.MC', 'CaixaBank', 'Finanzas', 'IBEX 35'),
  ('IAG.MC', 'International Consolidated Airlines', 'Industria', 'IBEX 35'),
  ('NTGY.MC', 'Naturgy', 'Energía', 'IBEX 35'),
  ('ELE.MC', 'Endesa', 'Energía', 'IBEX 35'),
  ('GRF.MC', 'Grifols', 'Salud', 'IBEX 35'),
  ('ACS.MC', 'ACS', 'Industria', 'IBEX 35'),
  ('RED.MC', 'Redeia', 'Energía', 'IBEX 35'),
  ('ENG.MC', 'Enagás', 'Energía', 'IBEX 35'),
  ('MAP.MC', 'Mapfre', 'Finanzas', 'IBEX 35'),
  ('BKT.MC', 'Bankinter', 'Finanzas', 'IBEX 35'),
  ('SAB.MC', 'Banco Sabadell', 'Finanzas', 'IBEX 35'),
  ('MRL.MC', 'Merlin Properties', 'Inmobiliario', 'IBEX 35'),
  ('COL.MC', 'Inmobiliaria Colonial', 'Inmobiliario', 'IBEX 35'),
  ('SCYR.MC', 'Sacyr', 'Industria', 'IBEX 35'),
  ('ANA.MC', 'Acciona', 'Industria', 'IBEX 35'),
  ('ANE.MC', 'Acciona Energía', 'Energía', 'IBEX 35'),
  ('LOG.MC', 'Logista', 'Industria', 'IBEX 35'),
  ('ROVI.MC', 'Laboratorios Rovi', 'Salud', 'IBEX 35'),
  ('FDR.MC', 'Fluidra', 'Industria', 'IBEX 35'),
  ('MTS.MC', 'ArcelorMittal', 'Materiales Básicos', 'IBEX 35'),
  ('ACX.MC', 'Acerinox', 'Materiales Básicos', 'IBEX 35'),
  ('IDR.MC', 'Indra Sistemas', 'Tecnología', 'IBEX 35'),
  ('UNI.MC', 'Unicaja Banco', 'Finanzas', 'IBEX 35'),
  ('SLR.MC', 'Solaria Energía y Medio Ambiente', 'Energía', 'IBEX 35'),
  ('MEL.MC', 'Meliá Hotels International', 'Consumo Cíclico', 'IBEX 35'),
  ('CAF.MC', 'Construcciones y Auxiliar de Ferrocarriles', 'Industria', 'Continuo'),
  ('DIA.MC', 'Distribuidora Internacional de Alimentación', 'Consumo Defensivo', 'Continuo'),
  ('ENC.MC', 'Ence Energía y Celulosa', 'Materiales Básicos', 'Continuo'),
  ('PHM.MC', 'PharmaMar', 'Salud', 'Continuo'),
  ('GEST.MC', 'Gestamp Automoción', 'Consumo Cíclico', 'Continuo'),
  ('VID.MC', 'Vidrala', 'Industria', 'Continuo'),
  ('TLGO.MC', 'Talgo', 'Industria', 'Continuo'),
  ('LLN.MC', 'Lleida.net', 'Telecomunicaciones', 'BME Growth'),
  ('GIG.MC', 'Gigas Hosting', 'Tecnología', 'BME Growth'),
  ('MAKS.MC', 'Making Science', 'Tecnología', 'BME Growth'),
  ('HLZ.MC', 'Holaluz', 'Energía', 'BME Growth')
ON CONFLICT (symbol) DO UPDATE SET
  name = EXCLUDED.name,
  sector = EXCLUDED.sector,
  market = EXCLUDED.market,
  updated_at = NOW();
