INSERT INTO public.assets (symbol, name, sector, market)
VALUES
  ('ANA.MC', 'Acciona', 'Utilities', 'IBEX 35'),
  ('ANE.MC', 'Acciona Energía', 'Utilities', 'IBEX 35'),
  ('ACX.MC', 'Acerinox', 'Basic Materials', 'IBEX 35'),
  ('ACS.MC', 'ACS', 'Industrials', 'IBEX 35'),
  ('AENA.MC', 'Aena', 'Industrials', 'IBEX 35'),
  ('AMS.MC', 'Amadeus', 'Technology', 'IBEX 35'),
  ('MTS.MC', 'ArcelorMittal', 'Basic Materials', 'IBEX 35'),
  ('SAB.MC', 'Banco Sabadell', 'Financials', 'IBEX 35'),
  ('SAN.MC', 'Banco Santander', 'Financials', 'IBEX 35'),
  ('BKT.MC', 'Bankinter', 'Financials', 'IBEX 35'),
  ('BBVA.MC', 'BBVA', 'Financials', 'IBEX 35'),
  ('CABK.MC', 'CaixaBank', 'Financials', 'IBEX 35'),
  ('CLNX.MC', 'Cellnex Telecom', 'Telecommunications', 'IBEX 35'),
  ('ENG.MC', 'Enagás', 'Utilities', 'IBEX 35'),
  ('ELE.MC', 'Endesa', 'Utilities', 'IBEX 35'),
  ('FER.MC', 'Ferrovial', 'Industrials', 'IBEX 35'),
  ('FDR.MC', 'Fluidra', 'Industrials', 'IBEX 35'),
  ('GRF.MC', 'Grifols', 'Healthcare', 'IBEX 35'),
  ('IAG.MC', 'IAG', 'Industrials', 'IBEX 35'),
  ('IBE.MC', 'Iberdrola', 'Utilities', 'IBEX 35'),
  ('ITX.MC', 'Inditex', 'Consumer Cyclicals', 'IBEX 35'),
  ('IDA.MC', 'Indra', 'Technology', 'IBEX 35'),
  ('COL.MC', 'Inmobiliaria Colonial', 'Real Estate', 'IBEX 35'),
  ('LOG.MC', 'Logista', 'Industrials', 'IBEX 35'),
  ('MAP.MC', 'Mapfre', 'Financials', 'IBEX 35'),
  ('MEL.MC', 'Meliá Hotels', 'Consumer Cyclicals', 'IBEX 35'),
  ('MRL.MC', 'Merlin Properties', 'Real Estate', 'IBEX 35'),
  ('NTGY.MC', 'Naturgy', 'Utilities', 'IBEX 35'),
  ('PUIG.MC', 'Puig', 'Consumer Cyclicals', 'IBEX 35'),
  ('RED.MC', 'Redeia', 'Utilities', 'IBEX 35'),
  ('REP.MC', 'Repsol', 'Energy', 'IBEX 35'),
  ('ROVI.MC', 'Rovi', 'Healthcare', 'IBEX 35'),
  ('SCYR.MC', 'Sacyr', 'Industrials', 'IBEX 35'),
  ('SLR.MC', 'Solaria', 'Utilities', 'IBEX 35'),
  ('TEF.MC', 'Telefónica', 'Telecommunications', 'IBEX 35'),
  ('UNI.MC', 'Unicaja Banco', 'Financials', 'IBEX 35'),
  ('A3M.MC', 'Atresmedia', 'Communication Services', 'Mercado Continuo'),
  ('CAF.MC', 'CAF', 'Industrials', 'Mercado Continuo'),
  ('CIE.MC', 'CIE Automotive', 'Consumer Cyclicals', 'Mercado Continuo'),
  ('EBRO.MC', 'Ebro Foods', 'Consumer Defensive', 'Mercado Continuo'),
  ('EDR.MC', 'eDreams ODIGEO', 'Consumer Cyclicals', 'Mercado Continuo'),
  ('ENO.MC', 'Elecnor', 'Industrials', 'Mercado Continuo'),
  ('ENC.MC', 'Ence', 'Basic Materials', 'Mercado Continuo'),
  ('FAE.MC', 'Faes Farma', 'Healthcare', 'Mercado Continuo'),
  ('FCC.MC', 'FCC', 'Industrials', 'Mercado Continuo'),
  ('GEST.MC', 'Gestamp', 'Consumer Cyclicals', 'Mercado Continuo'),
  ('GRE.MC', 'Grenergy Renovables', 'Utilities', 'Mercado Continuo'),
  ('LDA.MC', 'Línea Directa', 'Financials', 'Mercado Continuo'),
  ('MVC.MC', 'Metrovacesa', 'Real Estate', 'Mercado Continuo'),
  ('HOME.MC', 'Neinor Homes', 'Real Estate', 'Mercado Continuo'),
  ('OHLA.MC', 'OHLA', 'Industrials', 'Mercado Continuo'),
  ('PHM.MC', 'PharmaMar', 'Healthcare', 'Mercado Continuo'),
  ('PSG.MC', 'Prosegur', 'Industrials', 'Mercado Continuo'),
  ('TLGO.MC', 'Talgo', 'Industrials', 'Mercado Continuo'),
  ('TUB.MC', 'Tubacex', 'Basic Materials', 'Mercado Continuo'),
  ('VID.MC', 'Vidrala', 'Consumer Cyclicals', 'Mercado Continuo'),
  ('VIS.MC', 'Viscofan', 'Consumer Defensive', 'Mercado Continuo'),
  ('LLE.MC', 'Lleida.net', 'Technology', 'BME Growth'),
  ('GIG.MC', 'Gigas Hosting', 'Technology', 'BME Growth'),
  ('HLZ.MC', 'Holaluz', 'Utilities', 'BME Growth'),
  ('IZER.MC', 'Izertis', 'Technology', 'BME Growth'),
  ('MAKS.MC', 'Making Science', 'Technology', 'BME Growth'),
  ('ART.MC', 'Arteche', 'Industrials', 'BME Growth'),
  ('CLR.MC', 'Clerhp', 'Industrials', 'BME Growth'),
  ('END.MC', 'Endurance Motive', 'Industrials', 'BME Growth'),
  ('SNG.MC', 'SNGULAR', 'Technology', 'BME Growth')
ON CONFLICT (symbol) DO NOTHING;