-- Seed data for public.assets (Spanish Stock Market)
-- Includes comprehensively IBEX 35, Mercado Continuo, and BME Growth

INSERT INTO public.assets (symbol, name, sector, market) VALUES
('ACS.MC', 'ACS,ACTIVIDADES DE CONSTRUCCION', 'Industrials', 'IBEX 35'),
('ACX.MC', 'ACERINOX, S.A.', 'Basic Materials', 'IBEX 35'),
('AENA.MC', 'AENA, S.M.E., S.A.', 'Industrials', 'IBEX 35'),
('AMS.MC', 'AMADEUS IT GROUP, S.A.', 'Technology', 'IBEX 35'),
('ANA.MC', 'ACCIONA, S.A.', 'Industrials', 'IBEX 35'),
('BBVA.MC', 'BANCO BILBAO VIZCAYA ARGENTARIA', 'Financial Services', 'IBEX 35'),
('BKT.MC', 'BANKINTER, S.A.', 'Financial Services', 'IBEX 35'),
('CABK.MC', 'CAIXABANK, S.A.', 'Financial Services', 'IBEX 35'),
('CLNX.MC', 'CELLNEX TELECOM, S.A.', 'Real Estate', 'IBEX 35'),
('COL.MC', 'COLONIAL SFL, SOCIMI. S.A.', 'Real Estate', 'IBEX 35'),
('ELE.MC', 'ENDESA,S.A.', 'Utilities', 'IBEX 35'),
('ENG.MC', 'ENAGAS,S.A.', 'Utilities', 'IBEX 35'),
('FER.MC', 'FERROVIAL SE', 'Industrials', 'IBEX 35'),
('GRF.MC', 'GRIFOLS S.A.', 'Healthcare', 'IBEX 35'),
('IAG.MC', 'INTERNATIONAL CONSOLIDATED AIRLINES GROUP, S.A.', 'Industrials', 'IBEX 35'),
('IBE.MC', 'ACCIONES IBERDROLA', 'Utilities', 'IBEX 35'),
('ITX.MC', 'INDUSTRIA DE DISEÑO TEXTIL, S.A.', 'Consumer Cyclical', 'IBEX 35'),
('LOG.MC', 'COMPAÑÍA DE DISTRIBUCIÓN INTEGRAL LOGISTA HOLDINGS, S.A.', 'Industrials', 'IBEX 35'),
('MAP.MC', 'MAPFRE, S.A.', 'Financial Services', 'IBEX 35'),
('MEL.MC', 'MELIA HOTELS INTERNATIONAL, S.A', 'Consumer Cyclical', 'IBEX 35'),
('MRL.MC', 'MERLIN PROPERTIES SOCIMI, S.A.', 'Real Estate', 'IBEX 35'),
('NTGY.MC', 'NATURGY ENERGY GROUP, S.A.', 'Utilities', 'IBEX 35'),
('PUIG.MC', 'PUIG BRANDS, S.A.', 'Consumer Defensive', 'IBEX 35'),
('RED.MC', 'REDEIA CORPORACION, S.A.', 'Utilities', 'IBEX 35'),
('REP.MC', 'REPSOL,  S.A.', 'Energy', 'IBEX 35'),
('ROVI.MC', 'LABORATORIOS FARMACEUTICOS ROVI', 'Healthcare', 'IBEX 35'),
('SAB.MC', 'BANCO DE SABADELL', 'Financial Services', 'IBEX 35'),
('SAN.MC', 'BANCO SANTANDER S.A.', 'Financial Services', 'IBEX 35'),
('TEF.MC', 'TELEFONICA,S.A.', 'Communication Services', 'IBEX 35'),
('UNI.MC', 'UNICAJA BANCO, S.A.', 'Financial Services', 'IBEX 35'),
('VIS.MC', 'VISCOFAN, S.A.', 'Consumer Cyclical', 'IBEX 35'),
('ADX.MC', 'AUDAX RENOVABLES, S.A.', 'Utilities', 'Mercado Continuo'),
('AEDAS.MC', 'AEDAS HOMES, S.A', 'Real Estate', 'Mercado Continuo'),
('ALM.MC', 'ALMIRALL S.A.', 'Healthcare', 'Mercado Continuo'),
('AMP.MC', 'AMPER, S.A.', 'Technology', 'Mercado Continuo'),
('AZK.MC', 'AZKOYEN, S.A.', 'Industrials', 'Mercado Continuo'),
('CAF.MC', 'CONSTRUCCIONES Y AUXILIAR DE FERROCARRILES, S.A.RROCARRILES, S.A.', 'Industrials', 'Mercado Continuo'),
('CASH.MC', 'PROSEGUR CASH, S.A.', 'Industrials', 'Mercado Continuo'),
('CBAV.MC', 'CLINICA BAVIERA S.A.', 'Healthcare', 'Mercado Continuo'),
('CIE.MC', 'CIE AUTOMOTIVE, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('CLEO.MC', 'Compañia Levantina de Edificacion y Obras Publicas, S.A.', 'Industrials', 'Mercado Continuo'),
('DIA.MC', 'DISTRIBUIDORA INTERNACIONAL DE ', 'Consumer Defensive', 'Mercado Continuo'),
('DOM.MC', 'GLOBAL DOMINION ACCESS, S.A.', 'Technology', 'Mercado Continuo'),
('ECR.MC', 'ERCROS', 'Basic Materials', 'Mercado Continuo'),
('EDR.MC', 'EDREAMS ODIGEO, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('ENC.MC', 'ENCE ENERGIA Y CELULOSA, S.A.', 'Basic Materials', 'Mercado Continuo'),
('FCC.MC', 'ACCIONES FOMENTO DE CONSTRUCCIO', 'Industrials', 'Mercado Continuo'),
('GAM.MC', 'GENERAL DE ALQUILER DE MAQUINARIA, S.A.', 'Industrials', 'Mercado Continuo'),
('GRE.MC', 'GRENERGY RENOVABLES, S.A.', 'Industrials', 'Mercado Continuo'),
('HOME.MC', 'NEINOR HOMES, S.A.', 'Real Estate', 'Mercado Continuo'),
('IBG.MC', 'IBERPAPEL GESTION,S.A.', 'Basic Materials', 'Mercado Continuo'),
('ISUR.MC', 'INMOBILIARIA DEL SUR S.A.', 'Real Estate', 'Mercado Continuo'),
('MCM.MC', 'MIQUEL Y COSTAS & MIQUEL, S.A.', 'Basic Materials', 'Mercado Continuo'),
('MVC.MC', 'METROVACESA, S.A.', 'Real Estate', 'Mercado Continuo'),
('NEA.MC', 'NICOLAS CORREA', 'Industrials', 'Mercado Continuo'),
('NXT.MC', 'NUEVA EXPRESION TEXTIL, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('NYE.MC', 'NYESA VALORES CORPORACION S.A.', 'Real Estate', 'Mercado Continuo'),
('OLE.MC', 'DEOLEO, S.A.', 'Consumer Defensive', 'Mercado Continuo'),
('ORY.MC', 'ORYZON GENOMICS, S.A.', 'Healthcare', 'Mercado Continuo'),
('PHM.MC', 'PHARMA MAR, S.A.', 'Healthcare', 'Mercado Continuo'),
('PRM.MC', 'PRIM, S.A.', 'Healthcare', 'Mercado Continuo'),
('PSG.MC', 'PROSEGUR', 'Industrials', 'Mercado Continuo'),
('PVA.MC', 'PESCANOVA,S.A.', 'Consumer Defensive', 'Mercado Continuo'),
('REN.MC', 'RENTA CORPORACION REAL ESTATE, ', 'Real Estate', 'Mercado Continuo'),
('RJF.MC', 'LABORATORIO REIG JOFRE, S.A.', 'Healthcare', 'Mercado Continuo'),
('SOL.MC', 'SOLTEC POWER HOLDINGS, S.A.', 'Technology', 'Mercado Continuo'),
('TLGO.MC', 'TALGO, S.A.', 'Industrials', 'Mercado Continuo'),
('TRG.MC', 'TUBOS REUNIDOS S.A.', 'Basic Materials', 'Mercado Continuo'),
('TRE.MC', 'TECNICAS REUNIDAS S.A.', 'Industrials', 'Mercado Continuo'),
('TUB.MC', 'TUBACEX, S.A.', 'Basic Materials', 'Mercado Continuo'),
('VID.MC', 'VIDRALA, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('VOC.MC', 'VOCENTO', 'Communication Services', 'Mercado Continuo'),
('AGIL.MC', 'AGILE CONTENT, S.A.', 'Technology', 'BME Growth'),
('COM.MC', 'CATENON, S.A.', 'Industrials', 'BME Growth'),
('EIDF.MC', 'ENERGIA, INNOVACION Y DESARROLLO', 'Utilities', 'BME Growth'),
('ELZ.MC', 'ASTURIANA DE LAMINADOS, S.A', 'Industrials', 'BME Growth'),
('ENRS.MC', 'ENERSIDE ENERGY, S.A.', 'Industrials', 'BME Growth'),
('FACE.MC', 'FACEPHI BIOMETRIA, S.A.', 'Technology', 'BME Growth'),
('HLZ.MC', 'HOLALUZ CLIDOM S.A.', 'Utilities', 'BME Growth'),
('LLN.MC', 'LLEIDANETWORKS SERVEIS TELEMATI', 'Communication Services', 'BME Growth'),
('NTH.MC', 'NATURHOUSE HEALTH, S.A', 'Consumer Defensive', 'BME Growth'),
('PANG.MC', 'PANGAEA ONCOLOGY S.A.', 'Healthcare', 'BME Growth'),
('SEC.MC', 'SECUOYA  GRUPO DE COMUNICACION,', 'Communication Services', 'BME Growth'),
('SNG.MC', 'SINGULAR PEOPLE S.A.', 'Technology', 'BME Growth'),
('FLUI.MC', 'FLUIDRA, S.A.', 'Consumer Cyclical', 'IBEX 35'),
('SACY.MC', 'SACYR, S.A.', 'Industrials', 'IBEX 35'),
('APY.MC', 'APPLUS SERVICES, S.A.', 'Industrials', 'Mercado Continuo'),
('ATR.MC', 'ATRESMEDIA CORPORACION DE MEDIOS DE COMUNICACION, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('BDL.MC', 'BODEGAS RIOJANAS, S.A.', 'Consumer Defensive', 'Mercado Continuo'),
('BME.MC', 'BOLSAS Y MERCADOS ESPAÑOLES', 'Financial Services', 'Mercado Continuo'),
('EBS.MC', 'EBRO FOODS, S.A.', 'Consumer Defensive', 'Mercado Continuo'),
('ERC.MC', 'ERCROS, S.A.', 'Basic Materials', 'Mercado Continuo'),
('EZY.MC', 'EZENTIS, S.A.', 'Industrials', 'Mercado Continuo'),
('GCO.MC', 'GRUPO CATALANA OCCIDENTE, S.A.', 'Financial Services', 'Mercado Continuo'),
('HLM.MC', 'HOLALUZ-CLIDOM, S.A.', 'Utilities', 'Mercado Continuo'),
('LHD.MC', 'LOGISTA, S.A.', 'Industrials', 'Mercado Continuo'),
('MTY.MC', 'METROVACESA, S.A.', 'Real Estate', 'Mercado Continuo'),
('NHH.MC', 'NH HOTEL GROUP, S.A.', 'Consumer Cyclical', 'Mercado Continuo'),
('PRO.MC', 'PROSEGUR, S.A.', 'Industrials', 'Mercado Continuo'),
('QBT.MC', 'QUABIT INMOBILIARIA, S.A.', 'Real Estate', 'Mercado Continuo'),
('RDM.MC', 'BODEGAS RODA, S.A.', 'Consumer Defensive', 'Mercado Continuo'),
('SNC.MC', 'SNC-LAVALIN ESPAÑA', 'Industrials', 'Mercado Continuo'),
('SPS.MC', 'SEPES', 'Industrials', 'Mercado Continuo'),
('URB.MC', 'URBAS GRUPO FINANCIERO, S.A.', 'Real Estate', 'Mercado Continuo'),
('ZOT.MC', 'ZARDOYA OTIS, S.A.', 'Industrials', 'Mercado Continuo'),
('ALT.MC', 'ALTEA, S.A.', 'Real Estate', 'BME Growth'),
('AST.MC', 'ASTURIANA DE LAMINADOS, S.A.', 'Basic Materials', 'BME Growth'),
('ATYS.MC', 'ATREVIA, S.A.', 'Consumer Cyclical', 'BME Growth'),
('CCOM.MC', 'CUATROOCHENTA, S.A.', 'Technology', 'BME Growth'),
('CLER.MC', 'CLERHP ESTRUCTURAS, S.A.', 'Industrials', 'BME Growth'),
('GIG.MC', 'GIGAS HOSTING, S.A.', 'Technology', 'BME Growth'),
('GRN.MC', 'GRENERGY RENOVABLES, S.A.', 'Utilities', 'BME Growth'),
('IFC.MC', 'INFORMA D&B, S.A.U.', 'Technology', 'BME Growth'),
('ILL.MC', 'ILLUNION, S.A.', 'Industrials', 'BME Growth'),
('INK.MC', 'INKEMIA IUCT GROUP, S.A.', 'Healthcare', 'BME Growth'),
('KRE.MC', 'KROMEX, S.A.', 'Basic Materials', 'BME Growth'),
('LLE.MC', 'LLEIDA.NET, S.A.', 'Technology', 'BME Growth'),
('MAKX.MC', 'MAKING SCIENCE GROUP, S.A.', 'Technology', 'BME Growth'),
('MED.MC', 'MEDIASET ESPAÑA COMUNICACIÓN, S.A.', 'Consumer Cyclical', 'BME Growth'),
('MIO.MC', 'MIOGROUP, S.A.', 'Consumer Cyclical', 'BME Growth'),
('PROA.MC', 'PROA CAPITAL, S.A.', 'Financial Services', 'BME Growth'),
('TCR.MC', 'TECNOCOM, TELECOMUNICACIONES Y ENERGIA, S.A.', 'Technology', 'BME Growth'),
('TR1.MC', 'TIER1 TECHNOLOGY, S.A.', 'Technology', 'BME Growth'),
('VLN.MC', 'VALENCIANA DE TELEVISIÓN, S.A.', 'Consumer Cyclical', 'BME Growth'),
('YMB.MC', 'YUMBUS, S.A.', 'Consumer Cyclical', 'BME Growth')
ON CONFLICT (symbol) DO NOTHING;
